### ISSUE TITLE
Length of the best match question and matching fragment sequence

### ISSUE THREAD

**Issue by jfourquet2** [bioinformatics-centre/kaiju#103]
Hi,
I have a question about the length of the best match used for classification (column 4 of verbose mode). Is this length must correspond to the length of the "matching fragment sequence(s)" on the 7th column ? It seems it is not the case so I don't understand what is this "matching fragment sequence(s)".

Thanks a lot in advance for your answer !

**Comment by pmenzel** [comment]
Hi, the content in column 4 depends on the run mode. In MEM mode, it contains the length of the longest matching sequence, but in Greedy mode, it contains the match score. 

The default mode is Greedy mode (since version 1.6.0).
Also, it seems that I didn't update the README file correspondingly, which still says that MEM is the default mode. I will fix that..

**Comment by jfourquet2** [comment]
Thanks a lot for your answer, so I will run it with the MEM mode. With the MEM mode will I obtain in column 4 the number of characters of the sequence of the column 7 ?

**Comment by pmenzel** [comment]
Yes. Note that there could be multiple longest sequences in column 7 though.

**Comment by jfourquet2** [comment]
Thanks a lot, it works with -a mem !
