### ISSUE TITLE
Running twice kaiju not exactly the same result

### ISSUE THREAD

**Issue by jfourquet2** [bioinformatics-centre/kaiju#106]
Hello,
When I make the index database (`makeDB.sh -r -t 5`) and then I run `kaiju` with -a mem and `kaijuReport`, I have a first result:
```
0.000001	        1	Citrobacter sp. 86
 0.000001	        1	Actinoplanes sp. SE50
 0.000001	        1	Bacillus sp. ZY-1-1
 0.000001	        1	Acinetobacter sp. FDAARGOS_493
 0.000001	        1	Pseudomonas sp. LTGT-11-2Z
-------------------------------------------
 0.001862	     1525	Viruses
26.197508	 21456557	cannot be assigned to a species 
-------------------------------------------
25.875822	 21193084	unclassified
```

I run again the same command lines (`makeDB.sh`, `kaiju`, `kaijuReport`) on the same files in an other directory and I haven't exactly the same results:
```
 0.000001	        1	Citrobacter sp. 86
 0.000001	        1	Actinoplanes sp. SE50
 0.000001	        1	Bacillus sp. ZY-1-1
 0.000001	        1	Acinetobacter sp. FDAARGOS_493
 0.000001	        1	Pseudomonas sp. LTGT-11-2Z
-------------------------------------------
 0.001862	     1525	Viruses
26.193208	 21453032	cannot be assigned to a species 
-------------------------------------------
25.876027	 21193251	unclassified
```
Is there normal that these results aren't exactly the same ?

Thanks a lot in advance !

**Comment by jfourquet2** [comment]
The files generated by the `makeDB.sh -r -t 5` command haven't exactly the same size, so I think the difference comes from the database files but why this command didn't make the same files each time ?
Thanks a lot in advance !

**Comment by pmenzel** [comment]
In principle, each run of Kaiju should return the same results, when using the same database and Kaiju index.

So you run `makeDB.sh -r` twice and each time in a different folder?
How long time was between both?
The RefSeq database is updated continuously, and new Bacteria genome assemblies are added almost daily. So maybe you have a couple of new genomes in one folder, which were not in the database when you made the other one. You can check the number of files in the `genomes/` subfolder.

Another idea is that maybe some of the files did not download in one of the runs, due to connection loss etc. Again, check the number of files in the `genomes/` subfolder.

**Comment by jfourquet2** [comment]
Thanks for your answer !
Yes, I run `makeDB.sh -r` twice and the first time (5th february) I have 25232 files in the folder genomes whereas the second time I have 25212 files (8th february). So I have less files the second time than the first time. I will re-run the command a new time to see what is the effect. Where can we see the exact number version of RefSeq database ? Thanks a lot again !

**Comment by pmenzel** [comment]
There is not really a version number here. Kaiju just fetches the table with all assemblies from Bacteria (ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/bacteria/assembly_summary.txt) and Archaea, and downloads them.

**Comment by jfourquet2** [comment]
Ok, thanks for all your answers, it helps me a lot. I saw that last modification of these assemblies is today morning so I suppose that I will have an other number of files with my third run of the command `makeDB.sh -r`. Thanks again !
