### ISSUE TITLE
It is stucked makedb with RVDB extracting sequences. 

### ISSUE THREAD

**Issue by okapick** [bioinformatics-centre/kaiju#115]
Good morning. I am using the kaiju makedb with RVDB database. It is 8 hours doing the extraction sequences from the U-RVDBv15.1-prot.fasta.bz2. And the file kaiju_db_rvdv.faa is empty. Do you have some idea? Is it not the first time i used newest kaiju in my system.

Regards.

```
/kaiju sudo ./bin/kaiju-makedb -s rvdb -t 25
Downloading taxdump.tar.gz
.listing                [  <=>               ]   2.14K  9.22KB/s    in 0.2s    
2019-05-19 10:15:22 URL: ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz [2196] -> ".listing" [1]
taxdump.tar.gz      100%[===================>]  46.18M   349KB/s    in 2m 43s  
2019-05-19 10:18:07 URL: ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz [48425210] -> "taxdump.tar.gz" [1]
Extracting taxdump.tar.gz
Downloading RVDB
Downloading prot.accession2taxid.gz
.listing                [ <=>                ]   1.25K  --.-KB/s    in 0.004s  
2019-05-19 10:18:18 URL: ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.gz [1275] -> "rvdb/.listing" [1]
Unpacking prot.accession2taxid.gz
Extracting protein sequences from U-RVDBv15.1-prot.fasta.bz2

```

**Comment by pmenzel** [comment]
Hi,

the script that converts the RVDB-prot database is not really efficient memory-wise. It loads the whole prot.accession2id into RAM and since it is written in Perl, that will require a lot of memory.

I just measured it and it needed 126GB of RAM and run for 1h. So probably you don't have enough memory free and the machine tries to swap the memory to disk which will probably take a long time.
I uploaded my RVDB-kaiju database to the kaiju web server and you can download it [here](http://kaiju.binf.ku.dk/database/kaiju_db_rvdb_2019-05-19.tgz).
