### ISSUE TITLE
Kaiju to kraken report

### ISSUE THREAD

**Issue by sarah872** [bioinformatics-centre/kaiju#119]
is there a way to convert the kaiju report into a kraken-style report?

**Comment by pmenzel** [comment]
Hi, I think you can use the `kraken-report` script also on the kaiju output file.
Otherwise, use `kaiju2table` to create summary reports.

**Comment by sarah872** [comment]
`kraken-report` needs some kraken-specific database file. 
I need something that gives me the following:

```
 90.37  9411754 9411754 U       0       unclassified
  7.60  791374  0       -       1       root
  7.60  791374  0       -       131567    cellular organisms
  7.53  784231  1       D       2           Bacteria
  5.20  541610  11      P       1224          Proteobacteria
  3.66  380891  102     C       1236            Gammaproteobacteria
  1.22  126567  9       O       91347             Enterobacterales
  1.08  112366  3       F       1903411             Yersiniaceae
  1.07  111114  34      G       613                   Serratia
  1.04  107966  107966  S       615                     Serratia marcescens
```

**Comment by pmenzel** [comment]
Probably then you could use kaiju2table and run it once for each of the ranks that you need and paste the tables together.

**Comment by sarah872** [comment]
Not sure I can follow!
`kaiju2table` for phylum gives me output like this:

```
file	percent	reads	taxon_id	taxon_name
myfile	13.446650	1371979	1224	Proteobacteria
[...]
```

**Comment by pmenzel** [comment]
Yes, and you can run it also with all other ranks, so that you get the summarized abundances for each taxon at each rank.

**Comment by will-rowe** [comment]
I was after this feature too - was about to code something up when I found this:

[Kaiju_to_kraken](https://github.com/JeremieMG/Kaiju_to_kraken)

Works well - thanks @JeremieMG

**Comment by sarah872** [comment]
That's it! Thanks!
Unfortunately, the `kaijuReport` was removed from the last `kaiju` version.

**Comment by dnlrxn** [comment]
Is there an updated script to convert kaiju output to a pavian compatible "kreport" table? Thanks!

**Comment by mattheatley** [comment]
i've found a work around using krakentools. you can convert the kaiju output to a kreport using make_kreport.py so long as you have an suitable ktaxonomy file i.e. built using an appropraite seqid2taxid.map that corresponds with the library used by kaiju.

**Comment by Xinpeng021001** [comment]
> i've found a work around using krakentools. you can convert the kaiju output to a kreport using make_kreport.py so long as you have an suitable ktaxonomy file i.e. built using an appropriate seqid2taxid.map that corresponds with the library used by kaiju.

@mattheatley @dnlrxn Hi all, could you please share how to make a proper ktaxonomy file based on kaiju db? I don't found it in the kaiju db folder (the seqid2taxid.map) and when I use the kraken2 seqid2taxid.map, they are not matched with each other. Thank you in advance!

**Comment by masalgar** [comment]
Hi, I'm leaving this for future reference for anyone who needs this. I ran Kaiju with the nr_euk database, and I wanted to generate a Kraken style report to visualise my results on Pavian. I used krakentools for this.

To make the seqid2taxid.map file, I used this code on the .faa file I used to make the nr_euk database:

```bash
grep '^>' kaiju_db_nr_euk.faa \
  | sed 's/^>//' \
  | awk '{
      header=$0;
      # find last underscore
      pos = match(header, /_[^_]*$/);
      protein = substr(header, 1, pos-1);
      taxid   = substr(header, pos+1);
      print protein "\t" taxid;
    }' > seqid2taxid.map
```

This avoids having to build an entire Kraken2 database.

This script takes the sequence headers from *.faa and produces a table with two columns, following the format that `make_ktaxonomy` expects. Krakentools expects a 2-column tab-delimited file containing sequence IDs and taxonomy IDs.  This information is already in the sequence headers in the *.faa file, separated by an underscore, so it's relatively simple to split them. Some sequence IDs have underscores (WP_), so the script looks for the last underscore in the header to make sure it doesn't cut sequence IDs incorrectly.

Full disclaimer, I used copilot to figure this out and I haven't tested it with other databases. You can check the file with `head seqid2taxid.map` to see if it looks about right.

It takes a while to run, but the resulting file can be used with `make_ktaxonomy` alongside the same `names.dmp` and `nodes.dmp` that I used to build Kaiju's database. However, I ran into the problem that Bacteria, Eukarya, etc, were not being labelled as "domain", so Pavian was not displaying them correctly.

After more troubleshooting, I found out that the problem was `make_ktaxonomy`. It was not assigning the proper domain levels to Bacteria, Eukarya, etc. This happens because NCBI changed the way they rank different taxonomic levels last year, so now they use 'domain' rather than 'superkingdom' . I fixed it by editing the `make_ktaxomy.py` script on line 80. It originally looks like this:

```python
    map_ranks = {'superkingdom':'D',
        'phylum':'P',
        'class':'C',
        'order':'O',
        'family':'F',
        'genus':'G',
        'species':'S'}
```

I added the new domain designation. I also added acelullar root as a domain, meaning that viruses are assigned to a domain, for visualisation purposes on Pavian:

```python
    map_ranks = {'superkingdom':'D',
        'acellular root':'D',
        'domain':'D',
        'phylum':'P',
        'class':'C',
        'order':'O',
        'family':'F',
        'genus':'G',
        'species':'S'}
```

Once edited, you can run `make_ktaxonomy` as I described before, and then use `make_kreport` with your kaiju output. The result should load into Pavian just fine.
