### ISSUE TITLE
Can add human related proteins for metatranscriptomics taxonomic classification?

### ISSUE THREAD

**Issue by BigNianNGS** [bioinformatics-centre/kaiju#143]
Hi, 
I wonder if I can using kaiju for taxonomic classification by adding human related proteins along with microbial subset nr database. The sequences were from metatranscriptomics experiment of human respiratory tract samples, which may containing high abundance reads of human and microbes.

Thanks in advance.

**Comment by BigNianNGS** [comment]
And even using the total NR database ?

**Comment by pmenzel** [comment]
Hi,
adding human proteins to the kaiju database will not help much for identifying human reads, because proteins make up only a tiny percentage of the human genome.

Therefore, I recommend that you map all reads to the human genome, e.g. with bwa, and then extract the unmapped reads and only use those as input for kaiju with the normal kaiju_nr database.

**Comment by BigNianNGS** [comment]
Many thanks for perfect suggestion!
