### ISSUE TITLE
kaiju execution is hanging with mixed custom/refseq database

### ISSUE THREAD

**Issue by phlatphish** [bioinformatics-centre/kaiju#184]
I ran:

kaiju-makedb -s refseq

in order to get all the .faa files.  I added a set of my own .faa files to the source directory and rebuilt the index using:

kaiju-makedb -s refseq --index-only

It ran to completion without errors, and deposited the fmi file in the expected place.  All of my 34 custom bacterial .faa files are in the taxonomy, and the headers are formatted like:

>Frankia_asymbiotica_CDS_0001_1834516

I then execute:

kaiju -t $nodes_file -f $kaiju_index -i $fasta_file -o $outfile -v -z 16

where the variables are correctly filled in by the wrapper script.  It begins running and i can monitor the growth of the output file. At some point it stops growing but the process continues with no change in the memory or CPU usage.

Eventually I killed it, tried on different machines with different -z parameters, but the same thing always happens.  

When I make a small index just from my 34 favorite .faa files it runs to completion.

When I make an index just from the refseq set it runs ok  too.

None of the taxids in my set of 34 are duplicated in the refseq set.

Any assistance would be much apprecieated.

Thanks,
Callum

One more thing: when I run kaiju I get repeated warnings that some taxids are not in the taxonomy. However, those taxids are not in my custom set, so I assume are in the downloaded refseq data.

**Comment by pmenzel** [comment]
Hi,

that's quite weird, seems like a conflict between your custom files and the genomes in the RefSeq download.
I have no immediate intuition on what could be wrong.

Do you use the latest version of kaiju, where the SEG filter is enabled by default? Otherwise try adding option `-x`.

Does the same happen in mem-mode and greedy mode?

It is probably one particular query sequence, which causes the issue. What kind of sequences are in your input file?
Would it be possible to partition the input data until you nail it down?

Maybe I could try to reproduce it if you send me the faa files and the query sequences..

Peter

**Comment by phlatphish** [comment]
Thanks for getting back so quickly.  I too suspect there is something toxic in the input. I'll check for illegal chars etc. and split things up as you suggest. I'll reach out for help if that doesn't ID the problem. Much appreciated,
Callum

**Comment by pmenzel** [comment]
I can only imagine that somehwere the program flow enters a loop and doesn't terminate.
Did you modify nodes.dmp?

**Comment by phlatphish** [comment]
I was able to identify a sequence read that caused kaiju to hang with a particular index, by repeatedly splitting the input. However, the same read does not cause any problems with other indexes.  If you like I can put the read and the index and its input sequences into a tarfile and find a way to get it to you. Do you have an FTP site I could upload to?

I have another question I can open as a separate issue if that is better.  As an alternative to combining my genomes and refseq into a custom database I ran them separately with the idea of using kaiju-mergeOutputs on the two output files.  However, the two output files contain different numbers of records.  Shouldn't the outputs have one line per read, irrespective of the index?

**Comment by pmenzel** [comment]
> I was able to identify a sequence read that caused kaiju to hang with a particular index, by repeatedly splitting the input. However, the same read does not cause any problems with other indexes.  If you like I can put the read and the index and its input sequences into a tarfile and find a way to get it to you. Do you have an FTP site I could upload to?

Thanks for your efforts! Including the whole index would result in a quite big file.

Maybe I can reproduce the problem first, if you just send me your additional sequences and I add them to a freshly created RefSeq database and test that single read. Would your custom sequences fit into an e-mail?
Otherwise I will send you an upload-link by e-mail, if you send me an e-mail to pmenzel@gmail.com.

**Comment by pmenzel** [comment]
Resolved by removing non-amino acid characters from the custom fasta file before making the kaiju index.
