### ISSUE TITLE
Kaiju and Conda

### ISSUE THREAD

**Issue by rasmusagren** [bioinformatics-centre/kaiju#20]
Hi,

I've been trying to get Kaiju to work as a package in bioconda, but I've been having some problems with the makeDB script. The issue is explained here: https://bitbucket.org/snakemake/snakemake/issues/465/conda-and-symbolic-links. Could you maybe consider other solutions than using e.g. $SCRIPTDIR/convertNR, such as first checking if it's on PATH? Or maybe there can be a solution with readlink? Thanks!

Cheers,
Rasmus

**Comment by pmenzel** [comment]
Hej Rasmus,

yeah the makeDB.sh is a bit confusing; I used readlink before, but that is apparently not working on some MacOS. But you are right, the programs should be called via the PATH.

Would you try out the script attached here, where I just add the SCRIPTDIR to the PATH inside makeDB.sh. Then, the script should use any convertNR etc. that is found in the PATH prior to the one in SCRIPTDIR. I haven't tested a full run yet though. (Also it's zipped because of github).

Another option could be to use `make static` when compiling Kaiju in order to avoid the GLIBCXX problems..

cheers,
[makeDB.zip](https://github.com/bioinformatics-centre/kaiju/files/701454/makeDB.zip)


Peter

**Comment by rasmusagren** [comment]
Thanks a lot, but in order to add it to bioconda I'd need a more "official" version. Would you consider making a conda compatible branch or release if you don't want to change in master? It's up to you of course, but conda is really nice :)

**Comment by pmenzel** [comment]
If the modified makeDB.sh works for you, I would commit it to the master branch here.

So please test it, ideally with a full run through of `makeDB.sh -e` and `makeDB.sh -r or -p`.

thanks! :)

**Comment by rasmusagren** [comment]
Great, I try it out and get back to you then.

**Comment by rasmusagren** [comment]
Now I've tested and it builds without problems both for -e and -p.

**Comment by pmenzel** [comment]
Great! thanks for testing! Will commit it now.
