### ISSUE TITLE
differneces between Progenomes vs viruses databases

### ISSUE THREAD

**Issue by Joao-Gatica** [bioinformatics-centre/kaiju#201]
Hi
I tried to obtain a virus sample profile; for this, I used Progenomes and viruses databases and the results were highly different.
For example, the group Podoviridae, using Progenomes, represent 85% of all viruses; however, for the same sample, Podoviridae represent only 30% of all viruses when the viruses database was used. 
In addition, the number of reads mapped to viruses was 340,000 using Progenomes and for the same sample was 1,130,000 using the virus database.
What is the reason?, I suppose that the number of viruses contained in Progenomes is lower than the observed in the virus database, right?
Does this mean that Progenomes is not recommended for viruses? It is better to use the viruses database and run kaiju twice, once for bacteria and once for viruses?

Thank you for your comments
Joao

**Comment by pmenzel** [comment]
Hi,

>the number of reads mapped to viruses was 340,000 using Progenomes and for the same sample was 1,130,000 using the virus database.

I assume, that is because the sample also contained bacterial DNA? So when you use the virus-only database, a lot of bacterial reads are likely misclassified as viruses, but when using the progenomes database, they are classified to bacteria.
You could compare the alignment scores between both databases for some of the reads.

Generally, one should prefer a comprehensive as possible reference database, so that each read has the best chance to be assigned to the true origin, and therefore has no chance to be misclassified due to random sequence matches or due to weak homology.

**Comment by Joao-Gatica** [comment]
Thank you for your fast answer

You are right, our sample also contains bacterial DNA. I will take your advice regarding using a comprehensive reference database.

Joao
