### ISSUE TITLE
Segmentation fault in various lines

### ISSUE THREAD

**Issue by tarunaaggarwal** [bioinformatics-centre/kaiju#23]
Hello,

I'm running Kaiju on a cluster and I keep running into segfault issues. And different lines are causing this issue every time I run the script which is below and so is the error. Any ideas why this might be happening please?

SCRIPT:
```
#!/bin/bash

#SBATCH --job-name="kaiju"
#SBACTH --partition=batch
#SBATCH --nodes=1
#SBATCH --ntasks=32
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2G
#SBATCH --time=14-00:00:00
#SBATCH --mail-user=taruna.aggarwal@ucr.edu
#SBATCH --mail-type=END,FAIL
#SBATCH -e slurm-%j.err-%N
#SBATCH -o slurm-%j.out-%N

module load kaiju/f81d2ca
module load db-kaiju/20170113-e

#change these paths according to where the project files are
SEQS=/rhome/taruna/shared/GOMRI/data-clean/GOM_concat1.7_allF04combo_10Jan14.fna
OUT=/bigdata/biklab/taruna/gomri-kaiju.out

#change output directory name

kaiju \
-t $KAIJU_DB \
-f $KAIJU_DB \
-i $SEQS \
-o $OUT
``` 

ERROR:
```
/var/spool/slurmd/job99594/slurm_script: line 28:  7035 Segmentation fault      kaiju -t $KAIJU_DB -f $KAIJU_DB -i /rhome/taruna/shared/GOMRI/data
-clean/GOM_concat1.7_allF04combo_10Jan14.fna -o /bigdata/biklab/taruna/gomri-kaiju.out
```

Thanks for your help!

**Comment by pmenzel** [comment]
Hi,

From your message it is not really clear where the error occurs.

But I assume it is because you use the same value for options `-t` and `-f`. 
What is the content of $KAIJU_DB in your script? It looks like it is the directory that contains the index, while it should really be the paths to the files `nodes.dmp` for option `-t` and the database - depending on which option you used in makeDB.sh - either `kaiju_db.fmi`, `kaiju_db_nr.fmi`, or `kaiju_db_nr_euk.fmi` for option `-f`.

If this is really the case, then you could simply change the last line for example to  `... -t $KAIJU_DB/nodes.dmp -f $KAIJU_DB/kaiju_db.fmi`.

I also suggest to add options `-x` for low-complexity filtering, `-z 30` for using 30 parallel threads and `-a greedy -e 5` to increase sensitivity (but also runtime). 

cheers,
Peter

**Comment by tarunaaggarwal** [comment]
Well, that certainly did the trick! Thanks Peter!
