### ISSUE TITLE
Is it possible to include animals and plants in the classification?

### ISSUE THREAD

**Issue by feargalr** [bioinformatics-centre/kaiju#58]
For a mixed environmental sample, assembly indicates that there's non microbial DNA here. If I add in the correct taxon IDs to the taxonlist.tsv would that be sufficient to include animals and plants in the classification?

Thanks!

**Comment by pmenzel** [comment]
Hi,
yes that should work, but be aware of 
* increased RAM usage and size of the database, depending how many taxa you include.
* DNA of plants and animals has only a small percentage of protein-coding genes, most of their genomes are non-coding.

Peter

**Comment by feargalr** [comment]
RAM shouldn't be too much of an issue for me I think on this system, but I'll try and see how it goes. Thanks.

**Comment by feargalr** [comment]
Sorry to be a bother but is it possible to get KaijuReport to summarize these newly included taxonomic ranks based on things added into the taxonlist.tsv? Thanks

**Comment by pmenzel** [comment]
Hi,

I am not quite sure what you mean, can you provide more details, e.g. which command to you run and which output you get and what you expect to get instead?
Do you miss taxa in kaijuReport, but get them in the kaiju output file or in the krona chart?

**Comment by feargalr** [comment]
Sure. So I've built a kaiju database which includes metazoa and Viridiplantae. Everything works fine except KaijuReport will simply group them into "cannot be assigned to a phylum". I was just wondering if there was an easy fix for this?

**Comment by pmenzel** [comment]
Ok, maybe the taxa that you have in your samples are not assigned to a phylum in the NCBI taxonomy, so that when you run kaijuReport with phylum, it will not show up.
You can check that by searching the taxon id of some of your hits to the NCBi taxonomy browser.

For example, read algae are denoted as ["no rank"](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Tree&id=2763&lvl=3&keep=1), sitting below superkingdom and class levels. Therefore, everything assigned to this subtree does not have a phylum in that taxonomy.

**Comment by feargalr** [comment]
Thanks
