### ISSUE TITLE
Using kaijux for short-read sequence alignment to a protein database 

### ISSUE THREAD

**Issue by lihongyi123** [bioinformatics-centre/kaiju#65]
Hi Peter
I have a similar idea with issue #64. 

I am try to align short paired-end metagenomic reads to a protein database (a custom database). I  have searched such tools for half a day (https://en.wikipedia.org/wiki/List_of_sequence_alignment_software). Bowtie2, BWA, SOAP2 etc. only do DNA-DNA alignment; Diamond, Usearch or Vsearch, can do DNA-protein alignment, but not suitable for paired-end metagenomic reads. Can I use kaijux with greedy-5 mode for doing paired short-read sequence alignment? Any suggestions for the parameters?  
Is it possible to get a sam/bam file by the alignment as a feature in the future?  

More details about my case:
I have some metagenomic sequencing data of soil. I have them assembled using megahit and gene/protein predicted using prodigal which gives me the a gene database and corresponding a protein database (using cdhit, I can have non-redundant database). To calculate the abundances of the genes, I mapped the paired-end metagenomic reads back to the gene database using Bowtie2 with very sensitive mode, but less then 10% of the metagenomic reads were mapped (some samples were less than 5%; worse for using SOAP2). 
Since the assembling of metagenomic reads produces population genomes and so dose population genes. I think I can use protein database for mapping to increase the sensitivity just as you did in the taxonomy classification. I found no tool for such practice but kaijux. 

Hongyi

**Comment by pmenzel** [comment]
Hi Hongyi,
In principle you could use kaijux on your custom protein database, but note that kaijux treats paired-end reads independently from each other, so you will get two output lines per pair. So that would be like other programs, I suppose.

But in your case, it is probably not the right approach, since you should get a good mapping between your reads and the contigs assembled from them in the first place. The alignment via protein space is done to overcome evolutionary distances, which is not the reason for low mapping rate in your case.

It's weird that only few percent of your reads mapped backt to your assembly. Do you very short contigs and a high number of unassembled reads?

**Comment by lihongyi123** [comment]
Hi, Peter,
Thanks for your answer.
I know the pipeline using contigs for reads mapping and then protein prediction and annotation, and I have finished this analysis. Yes, them mapped well using Bowtie2 with very sensitive mode. Moreover, most reads were mapped to the contigs assembled form the same sample. This is not a problem for function annotation. 
Now I want to try CAG (Co-abundance genes) analysis. The original intention is to verify 16S sequencing and network analysis results. I found two co-abundance microbial clusters with significantly different functions (predicted by 16S) in the soils I studied. CAG analysis needs a non-redundant gene database (clustered using cd-hit with 95% identity) and their abundances in each sample. However, reads of different samples were kept mapping to different genes. I think this is the problem of evolutionary distances that genes do not cluster well. Moreover, cd-hit alway uses longer genes as representatives, this may lead to  low mapping rate of some samples with the same identity, since some samples gets better assembly and hence more genes selected as representatives. 
Low mapping rate is not a big problem since I can try more sensitive parameters or tools, but the  evolutionary distances is really a big trouble.

I think the alignment via protein may solve these problem. But if PE reads were treated independently, it will be difficult to deal with the output.

Maybe I will change the thinking of using CAG, and use the taxonomy results of kaiju to do co-abundance analysis. If I can get two clusters too, I can use reads of the two clusters for function analysis.

**Comment by pmenzel** [comment]
I am not sure if I understood everything you mentioned, but your issue seems to originate from mapping reads from one sample to the assembly of another sample, resulting bad mappings?

How about you, assemble each sample individually, cluster the proteins within each sample, map the reads for getting the abundance of each protein in the cluster.  Then, cluster all the proteins from all samples into one cluster and note the relationship between proteins and the cluster they are assigned to. In the end, this gives you a matrix of the abundances for all the proteins across the samples as input for your CAG test.

**Comment by lihongyi123** [comment]
That's a definitely good idea to solve some bias. I will give it a trial. 

Thanks so much to you, Peter.
