### ISSUE TITLE
Same number of results every time

### ISSUE THREAD

**Issue by koopkaup** [bioinformatics-centre/kaiju#77]
I ran kaiju using RefSeq database in greedy mode and got the same number (and exactly the same taxa) of results for every sample - 1072 genera and 35 phyla. It seems a little odd. I am guessing that kaiju found a match for every genome if the reference database. Maybe the default cutoff values are too low?

**Comment by pmenzel** [comment]
That could be the case.. You will have a certain percentage of reads that have no good match to anything, which will then be assigned randomly due to random matches. So if you have a lot of reads in your data, you will likely hit all possible genera, but with low abundance. You could also try the E-value filter, e.g. `-E 0.05` as an additional filter.

**Comment by koopkaup** [comment]
I will try that. But what is the default E-value level?

**Comment by koopkaup** [comment]
I also wrote a python script for merging kaiju report files of all the samples into one table. I am planning to add more options but maybe it is useful to somebody else too.
https://github.com/koopkaup/scripts/blob/master/python/kaiju_to_table.py

**Comment by pmenzel** [comment]
There is no default value for the E-value, you need to choose one using the option `-E`.
