### ISSUE TITLE
Creating a custom database using 6 frame translated nt sequence

### ISSUE THREAD

**Issue by dnieuw** [bioinformatics-centre/kaiju#78]
Dear kaiju team,

In an attempt to make kaiju more sensitive I would like to create a custom reference database using a six-frame translated nucleotide sequence. I saw that, in order to make a custom reference database, you need a fasta file containing only standard AA characters. The six-frame translation, however, contains many stop codons and "unknown" X amino acids. Could you give me some advice on how to make the six-frame translation AA reference database compatible with kaiju? I was thinking of simply removing the incompatible characters and/or split the "orfs" by stop-codon, but I'm not sure if that makes sense and is efficient when creating the bwt. 

Kind regards,

David Nieuwenhuijse

**Comment by pmenzel** [comment]
Hi,

you could use any of these options.
I would split the translated sequences at the stop codons. For the X characters, kaiju just removes them from the sequences when creating the databases in makeDB.sh.
That is because later only the 20 canonical a.a. chars are created anyway when translating the sequencing reads.

On the other hand it is possible to add more chars to the bwt/fmi, just add them to the list of chars passed to mkbwt.

**Comment by dnieuw** [comment]
Great, I indeed use the mkbwt to create my own database. I use my own references without using makeDB.sh so the X are still in there. I will just add the X to the list.
