### ISSUE TITLE
Kaiju not sending results via email

### ISSUE THREAD

**Issue by Mtd0053** [bioinformatics-centre/kaiju#97]

**Comment by Mtd0053** [comment]
Put through a number of files yesterday (Nov. 19)... and no email with results for the last three have been received. Details are all the same as prior uploads yesterday and other times..any idea how to get the results without reuploading the data again?

**Comment by pmenzel** [comment]
There are some terminated jobs from 19.11., that failed because of different length of the paired-end files. Not sure if these were yours, but you need to re-upload them if you want to give it another go. Remember to only upload one file (or two files for paired-end) at a time and do not use multiple tabs.

**Comment by Mtd0053** [comment]
Thanks for that! I'd been shutting the tab and just waiting for the emailed results, just saw if you leave the tab open it tells you about the pairing issue
I have a couple other questions (sorry, am new to metagenomics). Is there a script available to reverse the process, ie let me take the taxon names from the output and find out what sequences Kaiju is using to classify? Also, is there a script (R or something) that I can download so I can rearrange the Taxon Paths output into a usable framework to put into excel for use in R so I can run my models on the data? Sorry I have so many questions! Really appreciate any help!
